/**
 * Dragoman's managed block in the user's `~/.codex/config.toml`.
 *
 * Per-host network filtering is only enforceable through Codex's network proxy
 * plus a permission profile that lives in `config.toml` — verified against
 * codex-cli 0.150.1: the app-server `config` map does dotted *scalar* overrides
 * and can't inline-build a `[permissions]` table, and Codex reads the selected
 * profile ONCE at `thread/start` (a later `config.toml` change does not affect an
 * in-flight thread). So Dragoman maintains a single, self-documenting, delimited
 * block here that it OVERWRITES (never appends), so it can never accumulate, and
 * selects a profile per thread by posture.
 *
 * This module is pure string manipulation over the config text — the IO (reading
 * and atomically writing the file) is a thin layer above it, so the splice logic
 * is unit-tested against fixture config strings with no filesystem.
 */

/** Delimiters marking Dragoman's region. Everything between them is ours to rewrite. */
const BEGIN = "# >>> DRAGOMAN MANAGED (do not edit — regenerated by Dragoman) >>>";
const END = "# <<< DRAGOMAN MANAGED <<<";

export type DomainAction = "allow" | "deny";

/** The network axis of a profile: coarse on/off, plus optional per-host rules. */
export interface ProfileNetwork {
  /** Coarse switch — mirrors whether Claude's tools have network at all. */
  readonly enabled: boolean;
  /** Host → allow/deny. Non-empty needs the proxy to enforce; deny wins in Codex. */
  readonly domains: readonly (readonly [string, DomainAction])[];
}

/**
 * One Codex permission profile Dragoman manages — the sandbox/isolation axis as a
 * single unit: a built-in base scope plus the network rules. Selected per thread
 * via `thread/start`'s `permissions` field, it replaces the legacy `sandbox` enum
 * + `sandboxPolicy` object.
 */
export interface ManagedProfile {
  /** Profile id, selected per thread via `thread/start`'s `permissions` field. */
  readonly id: string;
  /** Built-in base profile to extend: `:read-only` · `:workspace` · `:danger-full-access`. */
  readonly base: string;
  /** Network rules; omit to leave the base's default network posture untouched. */
  readonly network?: ProfileNetwork;
}

/**
 * Render Dragoman's managed block: the network-proxy feature toggle (required for
 * domain rules to be enforced at all) and one `[permissions.<id>]` profile per
 * entry, each carrying its base and network domain rules. Pure.
 *
 * The block is ALL `[table]` sections — no bare root keys — so it is safe to
 * append after arbitrary user content (a bare key after the user's last table
 * would be absorbed into that table). `default_permissions`, the one root key
 * Codex needs once a `[permissions]` profile exists, is handled by the caller as
 * a prepend (see `codex-home`), not here.
 */
export function renderManagedBlock(profiles: readonly ManagedProfile[]): string {
  if (profiles.length === 0) return "";

  const lines: string[] = [BEGIN];
  // The proxy is what ENFORCES per-host rules, and it is global to the config, so
  // switch it on ONLY when some profile actually carries domain rules. No domains
  // ⇒ no proxy: network stays coarse on/off, behaviour is unchanged, and the
  // experimental proxy machinery never enters the path (the escape hatch).
  if (profiles.some(hasDomains)) {
    lines.push("[features.network_proxy]", "enabled = true", "");
  }
  for (const [index, profile] of profiles.entries()) {
    if (index > 0) lines.push("");
    lines.push(`[permissions.${profile.id}]`, `extends = ${tomlString(profile.base)}`);
    if (profile.network) {
      lines.push(`[permissions.${profile.id}.network]`, `enabled = ${profile.network.enabled}`);
      if (profile.network.domains.length > 0) {
        lines.push(`[permissions.${profile.id}.network.domains]`);
        for (const [host, action] of profile.network.domains) {
          lines.push(`${tomlString(host)} = ${tomlString(action)}`);
        }
      }
    }
  }
  lines.push(END);
  return lines.join("\n");
}

/** Whether a profile carries per-host domain rules (which require the proxy). */
function hasDomains(profile: ManagedProfile): boolean {
  return (profile.network?.domains.length ?? 0) > 0;
}

/**
 * Splice a freshly-rendered managed block into existing config text, replacing
 * any prior Dragoman block and preserving everything else verbatim. If no block
 * is present it is appended (separated by a blank line). Pure.
 */
export function spliceManagedBlock(existing: string, block: string): string {
  const stripped = stripManagedBlock(existing);
  if (block.trim() === "") return stripped; // nothing to add: just drop any prior block
  if (stripped.trim() === "") return block + "\n";
  return `${stripped.replace(/\n+$/, "")}\n\n${block}\n`;
}

/**
 * Remove Dragoman's managed block (and the blank lines hugging it) from config
 * text, leaving the user's own content untouched. Pure. A no-op when absent.
 */
export function stripManagedBlock(existing: string): string {
  const begin = existing.indexOf(BEGIN);
  if (begin === -1) return existing;
  const endMarker = existing.indexOf(END, begin);
  if (endMarker === -1) return existing; // malformed/half-written: leave it rather than guess
  const after = endMarker + END.length;
  const before = existing.slice(0, begin).replace(/\n+$/, "");
  const rest = existing.slice(after).replace(/^\n+/, "");
  if (before === "") return rest;
  if (rest === "") return before + "\n";
  return `${before}\n\n${rest}`;
}

/** Whether config text already sets a top-level `default_permissions` (outside our block). */
export function hasDefaultPermissions(existing: string): boolean {
  return /^\s*default_permissions\s*=/m.test(stripManagedBlock(existing));
}

/**
 * Ensure a root `default_permissions` is set, prepending one when the config has
 * none. Codex requires it once any `[permissions]` profile exists; it is a bare
 * root key, so it must lead the file (before any `[table]`) — hence prepend, not
 * append. Respects a value the user already carries. Pure.
 */
export function withDefaultPermissions(config: string, value: string): string {
  if (hasDefaultPermissions(config)) return config;
  return `default_permissions = ${tomlString(value)}\n${config}`;
}

/** A double-quoted TOML basic string, escaping backslashes and quotes. */
function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
