/**
 * Dragoman's managed block in the user's `~/.codex/config.toml`.
 *
 * Per-host network filtering is only enforceable through Codex's network proxy
 * plus a permission profile that lives in `config.toml` — verified against
 * codex-cli 0.150.1: the app-server `config` map does dotted *scalar* overrides
 * and can't inline-build a `[permissions]` table, and Codex reads the selected
 * profile ONCE at `thread/start` (a later `config.toml` change does not affect an
 * in-flight thread). So Dragoman maintains a single, self-documenting, delimited
 * block here that it OVERWRITES (never appends), so it can never accumulate, and
 * selects a profile per thread by posture.
 *
 * This module is pure string manipulation over the config text — the IO (reading
 * and atomically writing the file) is a thin layer above it, so the splice logic
 * is unit-tested against fixture config strings with no filesystem.
 */

/** Delimiters marking Dragoman's region. Everything between them is ours to rewrite. */
const BEGIN = "# >>> DRAGOMAN MANAGED (do not edit — regenerated by Dragoman) >>>";
const END = "# <<< DRAGOMAN MANAGED <<<";

export type DomainAction = "allow" | "deny";

/** One Codex permission profile Dragoman manages: a built-in base + network domain rules. */
export interface ManagedProfile {
  /** Profile id, selected per thread via `thread/start`'s `permissions` field. */
  readonly id: string;
  /** Built-in base profile to extend: `:read-only` · `:workspace` · `:danger-full-access`. */
  readonly base: string;
  /** Host → allow/deny. Order-preserving; deny wins in Codex regardless of order. */
  readonly domains: readonly (readonly [string, DomainAction])[];
}

export interface RenderOptions {
  /**
   * The `default_permissions` to emit. Codex requires it once ANY `[permissions]`
   * profile exists; set it to preserve the user's normal (non-Dragoman) default —
   * their existing value if they have one, else a built-in like `:workspace`.
   * Omit to emit none (only safe when the user already sets it outside our block).
   */
  readonly defaultPermissions?: string;
}

/**
 * Render Dragoman's managed block: the network-proxy feature toggle (required for
 * domain rules to be enforced at all) and one `[permissions.<id>]` profile per
 * entry, each carrying its base and network domain rules. Pure.
 */
export function renderManagedBlock(profiles: readonly ManagedProfile[], options: RenderOptions = {}): string {
  const lines: string[] = [BEGIN];
  if (options.defaultPermissions !== undefined) {
    lines.push(`default_permissions = ${tomlString(options.defaultPermissions)}`);
  }
  // Domain rules are silently ignored unless the proxy is enabled.
  lines.push("", "[features.network_proxy]", "enabled = true");
  for (const profile of profiles) {
    lines.push("", `[permissions.${profile.id}]`, `extends = ${tomlString(profile.base)}`);
    lines.push(`[permissions.${profile.id}.network]`, "enabled = true");
    if (profile.domains.length > 0) {
      lines.push(`[permissions.${profile.id}.network.domains]`);
      for (const [host, action] of profile.domains) {
        lines.push(`${tomlString(host)} = ${tomlString(action)}`);
      }
    }
  }
  lines.push(END);
  return lines.join("\n");
}

/**
 * Splice a freshly-rendered managed block into existing config text, replacing
 * any prior Dragoman block and preserving everything else verbatim. If no block
 * is present it is appended (separated by a blank line). Pure.
 */
export function spliceManagedBlock(existing: string, block: string): string {
  const stripped = stripManagedBlock(existing);
  if (stripped.trim() === "") return block + "\n";
  return `${stripped.replace(/\n+$/, "")}\n\n${block}\n`;
}

/**
 * Remove Dragoman's managed block (and the blank lines hugging it) from config
 * text, leaving the user's own content untouched. Pure. A no-op when absent.
 */
export function stripManagedBlock(existing: string): string {
  const begin = existing.indexOf(BEGIN);
  if (begin === -1) return existing;
  const endMarker = existing.indexOf(END, begin);
  if (endMarker === -1) return existing; // malformed/half-written: leave it rather than guess
  const after = endMarker + END.length;
  const before = existing.slice(0, begin).replace(/\n+$/, "");
  const rest = existing.slice(after).replace(/^\n+/, "");
  if (before === "") return rest;
  if (rest === "") return before + "\n";
  return `${before}\n\n${rest}`;
}

/** Whether config text already sets a top-level `default_permissions` (outside our block). */
export function hasDefaultPermissions(existing: string): boolean {
  return /^\s*default_permissions\s*=/m.test(stripManagedBlock(existing));
}

/** A double-quoted TOML basic string, escaping backslashes and quotes. */
function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
